add some unit and integration tests
  - various webapp integration tests with sass-only and compass modules
  - a unit test for the compiler mojo

Also updates in the travis script, coveralls reporting.
Guava 18 was dropped, as it's causing a conflict in the property
injection with the following exception:

```
java.lang.IllegalAccessError: tried to access method
com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap;
	 from class com.google.inject.internal.Annotations$AnnotationChecker
```

guava is still available as transitive through the maven-core